name: News Auto-Promote (every 60 min)

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  auto-promote:
    runs-on: ubuntu-latest
    steps:
      - name: Wake promote endpoint
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
        run: |
          echo "Waking promote endpoint..."
          curl -fsS "${SITE_URL}/api/news/promote" || exit 1
