name: News Ingest (every 30 min)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/news/ingest
        shell: bash
        run: |
          set -e
          URL="${{ secrets.SITE_URL }}/api/news/ingest"
          echo "GET $URL"
          # salva corpo em out.json e captura status
          HTTP_CODE=$(curl -sS -w "%{http_code}" -o out.json "$URL" || echo "000")
          echo "HTTP $HTTP_CODE"
          echo "----- body -----"
          cat out.json || true
          echo "----------------"
          # Não falha o job se der 4xx/5xx (somente loga)
          exit 0
